---
- name: Print Debug Message
  hosts: all
  tasks:
    - name: Display Debug Message
      debug:
        msg: "Hello, this is a debug message from Ansible."
    - name: Display Python install
      

...



