- name: Installation and configuration of web server
  hosts: all
  tasks:
    - name: Install web server package (RedHat)
      package:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install web server package (Debian)
      package:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Start and enable web server service (RedHat)
      systemd:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start and enable web server service (Debian)
      systemd:
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == "Debian" 
